### ISSUE TITLE
bonjour ma page héberge sur GitHub.io ne s affiche pas 

### ISSUE THREAD

**Issue by ananas122** [parti-renaissance/espace-adherent#9266]
b

**Comment by ottaviano** [comment]
Bonjour @ananas122, de quelle page parlez vous?

**Comment by ottaviano** [comment]
il me semble qu'il s'agit d'une erreur de repository vu le message initial, je ferme l'issue

![image](https://github.com/parti-renaissance/espace-adherent/assets/4582866/8441a52e-fce4-4679-8283-1c698567faab)
